// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ---- //
// SR04 //
// ---- //

#define SR04_wrap_target 0
#define SR04_wrap 9

static const uint16_t SR04_program_instructions[] = {
            //     .wrap_target
    0x2020, //  0: wait   0 pin, 0                   
    0xb723, //  1: mov    x, null                [23]
    0xb042, //  2: nop                           [16]
    0x20a0, //  3: wait   1 pin, 0                   
    0x0045, //  4: jmp    x--, 5                     
    0x0029, //  5: jmp    !x, 9                      
    0x00c4, //  6: jmp    pin, 4                     
    0xa0c9, //  7: mov    isr, !x                    
    0x8020, //  8: push   block                      
    0x0000, //  9: jmp    0                          
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program SR04_program = {
    .instructions = SR04_program_instructions,
    .length = 10,
    .origin = -1,
};

static inline pio_sm_config SR04_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + SR04_wrap_target, offset + SR04_wrap);
    return c;
}
#endif

